"""Generate CODEOWNERS."""

from __future__ import annotations

from .model import Config, Integration

BASE = """
# This file is generated by script/hassfest/codeowners.py
# People marked here will be automatically requested for a review
# when the code that they own is touched.
# https://github.com/blog/2392-introducing-code-owners
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

# SmartHub Core
.core_files.yaml @smart-hub/core
.git-blame-ignore-revs @smart-hub/core
.gitattributes @smart-hub/core
.gitignore @smart-hub/core
.hadolint.yaml @smart-hub/core
.pre-commit-config.yaml @smart-hub/core
.prettierignore @smart-hub/core
.yamllint @smart-hub/core
pyproject.toml @smart-hub/core
requirements_test.txt @smart-hub/core
/.devcontainer/ @smart-hub/core
/.github/ @smart-hub/core
/.vscode/ @smart-hub/core
/smarthub/*.py @smart-hub/core
/smarthub/auth/ @smart-hub/core
/smarthub/backports/ @smart-hub/core
/smarthub/helpers/ @smart-hub/core
/smarthub/scripts/ @smart-hub/core
/smarthub/util/ @smart-hub/core
/pylint/ @smart-hub/core
/script/ @smart-hub/core

# SmartHub Supervisor
.dockerignore @smart-hub/supervisor
build.json @smart-hub/supervisor
/machine/ @smart-hub/supervisor
/rootfs/ @smart-hub/supervisor
/Dockerfile @smart-hub/supervisor

# Other code
/smarthub/scripts/check_config.py @kellerza

# Integrations
""".strip()

INDIVIDUAL_FILES = """
# Individual files
/smarthub/components/demo/weather.py @fabaff
"""

REMOVE_CODEOWNERS = """
# Remove codeowners from files
/smarthub/components/*/translations/
"""


def generate_and_validate(integrations: dict[str, Integration], config: Config) -> str:
    """Generate CODEOWNERS."""
    parts = [BASE]

    for domain in sorted(integrations):
        integration = integrations[domain]

        if integration.integration_type == "virtual":
            continue

        codeowners = integration.manifest["codeowners"]

        if not codeowners:
            continue

        for owner in codeowners:
            if not owner.startswith("@"):
                integration.add_error(
                    "codeowners", "Code owners need to be valid GitHub handles."
                )

        parts.append(f"/smarthub/components/{domain}/ {' '.join(codeowners)}")

        if (config.root / "tests/components" / domain / "__init__.py").exists():
            parts.append(f"/tests/components/{domain}/ {' '.join(codeowners)}")

    parts.append(f"\n{INDIVIDUAL_FILES.strip()}")
    parts.append(f"\n{REMOVE_CODEOWNERS.strip()}")

    return "\n".join(parts)


def validate(integrations: dict[str, Integration], config: Config) -> None:
    """Validate CODEOWNERS."""
    codeowners_path = config.root / "CODEOWNERS"
    config.cache["codeowners"] = content = generate_and_validate(integrations, config)

    if config.specific_integrations:
        return

    if codeowners_path.read_text() != content + "\n":
        config.add_error(
            "codeowners",
            "File CODEOWNERS is not up to date. Run python3 -m script.hassfest",
            fixable=True,
        )


def generate(integrations: dict[str, Integration], config: Config) -> None:
    """Generate CODEOWNERS."""
    codeowners_path = config.root / "CODEOWNERS"
    codeowners_path.write_text(f"{config.cache['codeowners']}\n")
